name: Config Import
description: Clever configuration import.
package: Configuration
type: module
core: 8.x
core_version_requirement: ^8 || ^9

test_dependencies:
  - features (>=8.x-3.x-dev)

# Information added by Drupal.org packaging script on 2020-08-03
version: '8.x-1.7'
project: 'confi'
datestamp: 1596448274
